name: workflow.yml
on:
  push:
    branches:
      - main

jobs:
  integration:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch all history for accurate results of code analysis

      - name: Install required tools
        run: |
          dotnet tool install --global dotnet-reportgenerator-globaltool
          dotnet tool install --global dotnet-stryker

      - name: Run unit tests
        run: |
          dotnet test --collect:"XPlat Code Coverage" --results-directory TestResults

      - name: Generate report
        run: |
          reportgenerator -reportsTestResults/**/coverage.cobertura.xml -targetdir:coverage-report -reporttypes:Html

      - name: Run Mutation Tests
        run: |
          stryker

      - name: Collect Coverage Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Coverage Report
          path: coverage-report

      - name: Collect Stryker Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Stryker Report
          path: stryker-output